export const UPDATE_SELECT_CATEGORY = "UPDATE_SELECT_CATEGORY";
export const TRIVIA_RESET = "TRIVIA_RESET";

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_QUESTION = "GET_QUESTION";
export const LOAD_QUESTION = "LOAD_QUESTION";
export const UPDATE_NEW_SCORE = "UPDATE_NEW_SCORE";
export const UPDATE_FAILED_QUESTIONS = "UPDATE_FAILED_QUESTIONS";
export const UPDATE_REMAINING_QUESTIONS = "UPDATE_REMAINING_QUESTIONS";
export const UPDATE_PERCENTAGE_COMPLETION = "UPDATE_PERCENTAGE_COMPLETION";
export const QUIZ_COMPLETION = "QUIZ_COMPLETION"
export const QUIZ_RESET = "QUIZ_RESET";